# Generated by Django 4.2.2 on 2023-06-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registeruser',
            new_name='User',
        ),
    ]
