# Generated by Django 4.2.2 on 2023-06-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0002_rename_registeruser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
