# Generated by Django 4.2.2 on 2023-06-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagetotext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.CharField(max_length=100)),
                ('image_file', models.FileField(upload_to='imagetext')),
            ],
        ),
    ]
