# Generated by Django 4.2.2 on 2023-06-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0004_imagetotext'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetotext',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user_flow.user'),
            preserve_default=False,
        ),
    ]
